3 update our existing themes
fatthemes/pencil pull request #63
Opened 2024-04-26 10:32 UTC by DivyanshKhanna26

2024-04-29 05:35 UTC, limestreet requested changes

2024-04-29 05:35 UTC, limestreet commented on .github/workflows/push.yml
> +        run: php -v
I would remove those 2 lines for now :) they have clearly wrong indentation :)

2024-05-07 06:42 UTC, limestreet commented
@DivyanshKhanna26 so we have screenshot update here, right?
Looks good :)

2024-05-07 06:44 UTC, DivyanshKhanna26 commented
> @DivyanshKhanna26 so we have screenshot update here, right? Looks good :)

Yes.
I am just checking scss references in the theme. will delete it and then remove the folder.

2024-05-07 06:53 UTC, limestreet commented
@DivyanshKhanna26 I believe we may remove the folder, there should be no issues...
However, as you suggest - there maybe some refernces which may be simply not needed anymore:
- not sure about slick.css - is it included in style.css or loaded separatelly? Probably loaded separately, so need to stay
- gruntfile - the part related to scss generation and watch directive might be not needed
- another thing comming to my mind is autoprefixer part in gruntfile  - it adds prefixes on build time... so not sure if we need that, but currently generated on built style.css may be different that the one in repository, so maybe we should copy it from build to repo and submit pr? I'm curious if this one attached in zip here -> https://github.com/fatthemes/pencil/releases/tag/v1.6.4 is different than the one in repo.

2024-05-07 10:06 UTC, DivyanshKhanna26 commented
> * another thing comming to my mind is autoprefixer part in gruntfile  - it adds prefixes on build time... so not sure if we need that, but currently generated on built style.css may be different that the one in repository, so maybe we should copy it from build to repo and submit pr
I checked the css files after they were generated and there is no difference between the generated and the one we have pushed.

Also I have removed the scss code

2024-05-07 10:14 UTC, limestreet commented
@DivyanshKhanna26 
I see .netbeans.xml config file... I believe we may remove that too... I used netbeans years ago.

2024-05-07 10:15 UTC, limestreet commented
@DivyanshKhanna26 and style.css.map we may probably remove as well... it should map .scss to .css generation rules, so probbaly no longer needed

2024-05-13 11:39 UTC, limestreet commented on .gitignore
> +composer.lock
@DivyanshKhanna26 missing empty line at the end :)

2024-05-13 11:40 UTC, limestreet requested changes
@DivyanshKhanna26 we need to bump version in Pencil, as I will need to upload it to wp repo. And there is 1.6.4 already -> https://wordpress.org/themes/pencil/
I think we may bump it to **v1.7.0** as there is quite big clean-up.

2024-05-22 10:44 UTC, merged